### ISSUE TITLE
Question about extract rotation invariant feature from image

### ISSUE THREAD

**Issue by willard-yuan** [CPBridge/RIFeatures#1]
Hi @CPBridge, I tries to extract rotation invariant HOG feature and find your package that have implement the Fourier HOG Descriptor. In the example of [rotinv_test.cpp](https://github.com/CPBridge/RIFeatures/blob/master/example/rotinv_test.cpp), a first 20 points is shown to get the values of the derived rotation invariant features, and finally 20-d feature is extracted.  I reference your example to extract the rotation invariant HOG feature from single image, but I have no idea how to set the `image_locations.size()`. Would you like to give me some help so that I can extract the feature?

**Comment by CPBridge** [comment]
Hi @willard-yuan , I think you've slightly misunderstood what's going on in that example. What it does is extract a **single 1D feature** from **20 different places** in the image (image locations).

So the `image_locations` vector can be **any size** you want (however many image locations you are interested in finding a feature value for). By contrast the `query_feature_index` variable selects which feature you want at that location (there are `feature_extractor.getNumDerivedFeats()` possible features, so you can choose any integer between 0 and `feature_extractor.getNumDerivedFeats() - 1` inclusive).

Let me know if this helps. I hope the comments in the example source code are clear, but if there's something that you find confusing, please let me know so I can change it for others.

Chris

**Comment by willard-yuan** [comment]
@CPBridge Very thanks for your reply and it's helpful for me to understand the feature extraction. 

So to extract a 'global' feature from an image, I need to go through all the image locations ( point(x, y) ), extract the 1-D features, and concat all the 1-D features, just like the standard HOG feature (extract histgram of oritation of each cell and concat them)? 

I have two images, and the content of them is the same, but one image rotates some degrees, such as 45° or 90°. I want to to compare the two images similarity by the rotation invariant feature. I believe using the invariant feature, the two images will be very similar.

**Comment by CPBridge** [comment]
I'm glad it makes more sense now :)

Be aware that this methodology is not particularly well suited to global image features, as it inherently works on circular image patches and creates features that are invariant to the rotation **of that patch**. If you simply concatenate features calculated from the different patches in the image as you are suggesting, then the order of the features will be totally different if the image rotates and your feature vectors won't match at all (this is precisely the problem that the method is trying to solve!). I recommend that you read the article by Liu et al if you want a more detailed understanding of the method.

**Comment by willard-yuan** [comment]
Thanks for you helpful suggestion. I have read Liu's paper roughly, and I think it's better for me to read it carefully.

Thanks agagin.
